"""Plan definitions and AMA pricing."""

from typing import Any

# PLANAM 2026 (DR-001): 3-day trial, 50 welcome AMS — see docs/PLANAM_2026_DECISION_RECORD.md
TRIAL_DAYS = 3
TRIAL_MENU_GENERATIONS = 5
TRIAL_WELCOME_AMS = 50

# AMA costs for expensive AI actions (not navigation / CRUD views).
AMA_COSTS: dict[str, int] = {
    "nutritionist_ask": 2,
    "menu_generation_extra": 5,
    "menu_replace_dish": 3,
    "ocr_receipt": 4,
    "voice_command": 3,
    "deep_nutrition_analysis": 8,
    "menu_rebuild": 5,
    "ai_report": 10,
    "recipe_analyze": 2,
    "recipe_improve": 3,
    "bot_parse_text": 1,
    "event_plan_ai": 8,
}

PLAN_SEEDS: list[dict[str, Any]] = [
    {
        "code": "trial",
        "name": "Пробный",
        "price_rub": 0,
        "max_profiles": 1,
        "monthly_menu_generations": TRIAL_MENU_GENERATIONS,
        "monthly_ams": TRIAL_WELCOME_AMS,
        "sort_order": 0,
        "features": {
            "shopping": True,
            "pantry": True,
            "notifications": True,
            "nutrition_profile": True,
            "nutritionist_basic": True,
            "nutritionist_extended": False,
            "family_mode": False,
            "virtual_members": False,
            "ocr_receipts": "limited",
            "voice_commands": "limited",
            "macros": False,
            "sport_goals": False,
            "ai_care": False,
        },
    },
    {
        "code": "personal",
        "name": "Личный",
        "price_rub": 249,
        "max_profiles": 1,
        "monthly_menu_generations": 50,
        "monthly_ams": 200,
        "sort_order": 1,
        "features": {
            "shopping": True,
            "pantry": True,
            "notifications": True,
            "nutrition_profile": True,
            "nutritionist_basic": True,
            "nutritionist_extended": False,
            "family_mode": False,
            "virtual_members": False,
            "ocr_receipts": "limited",
            "voice_commands": "limited",
            "macros": False,
            "sport_goals": False,
            "ai_care": False,
        },
    },
    {
        "code": "shared",
        "name": "Совместный",
        "price_rub": 399,
        "max_profiles": 3,
        "monthly_menu_generations": 60,
        "monthly_ams": 300,
        "sort_order": 2,
        "features": {
            "shopping": True,
            "pantry": True,
            "notifications": True,
            "nutrition_profile": True,
            "nutritionist_basic": True,
            "family_mode": True,
            "shared_lists": True,
            "virtual_members": False,
            "ocr_receipts": "limited",
            "voice_commands": "limited",
            "macros": False,
            "sport_goals": False,
            "ai_care": False,
        },
    },
    {
        "code": "family",
        "name": "Семейный",
        "price_rub": 599,
        "max_profiles": 6,
        "monthly_menu_generations": 70,
        "monthly_ams": 400,
        "sort_order": 3,
        "features": {
            "shopping": True,
            "pantry": True,
            "notifications": True,
            "family_notifications": True,
            "nutrition_profile": True,
            "nutritionist_basic": True,
            "family_mode": True,
            "family_roles": True,
            "virtual_members": True,
            "shared_lists": True,
            "ocr_receipts": "limited",
            "voice_commands": "limited",
            "macros": False,
            "sport_goals": False,
            "ai_care": False,
        },
    },
    {
        "code": "pro",
        "name": "ПланАм PRO",
        "price_rub": 999,
        "max_profiles": 15,
        "monthly_menu_generations": None,
        "monthly_ams": 500,
        "sort_order": 4,
        "features": {
            "shopping": True,
            "pantry": True,
            "notifications": True,
            "family_notifications": True,
            "nutrition_profile": True,
            "nutritionist_basic": True,
            "nutritionist_extended": True,
            "family_mode": True,
            "family_roles": True,
            "virtual_members": True,
            "shared_lists": True,
            "ocr_receipts": True,
            "voice_commands": True,
            "macros": True,
            "sport_goals": True,
            "weight_progress": True,
            "auto_planning": True,
            "finance_analytics": True,
            "ai_care": True,
        },
    },
]
